Implement Netuitive Reporter
Netuitive/dropwizard-metrics pull request #1
Opened 2017-02-09 17:51 UTC by joepusateri

Initial implementation of Netuitive Dropwizard Reporter to StatsD

2017-02-10 13:14 UTC, TheConnMan requested changes

2017-02-10 13:14 UTC, TheConnMan commented on README.md
> +`./run_tests.sh`
Where are these tests?

2017-02-10 13:14 UTC, TheConnMan commented on README.md
> +docker-compose up -d --build
This fails after a clean `git clone`. The dropwizard example application does a COPY of a .jar which is expected to be prebuilt. The Dockerfile should build the example app within the container.

2017-02-10 13:14 UTC, TheConnMan commented on src/main/java/io/dropwizard/metrics/NetuitiveMetricsReporter.java
> +    	pushGauge(metricName + ".1MinuteRate", meter.getOneMinuteRate());
Should metric names have any caps in them? I tend to see only lower case metric FQNs.

2017-02-10 13:14 UTC, TheConnMan commented on src/test/docker/docker-compose.yml
> +    image: example/dropwizard
Only one of build and image should be used in a `docker-compose.yml` file, so this image line shouldn't be here.

2017-02-10 13:14 UTC, TheConnMan commented on src/test/docker/docker-dropwizard-example/README.md
> +* JDK (to compile java file locally)
Requiring a JDK and Gradle for a local Docker build is against best practice.

2017-02-10 13:14 UTC, TheConnMan commented on src/test/docker/docker-dropwizard-example/dockerBuildImage.bat
> +docker build -t example/dropwizard:latest .
Why are helper bat/sh necessary? These should just be in the docs (as it looks like they are).

2017-02-10 14:45 UTC, joepusateri commented on README.md
> +docker-compose up -d --build
I had not checked in the built jars.  Instructions in the docker example project shows how to build via gradle.  This readme is about using the library in the user's project.  More Readme changes expected via Jordan

2017-02-10 14:46 UTC, joepusateri commented on README.md
> +`./run_tests.sh`
User to provide their own tests

2017-02-10 14:46 UTC, joepusateri commented on src/main/java/io/dropwizard/metrics/NetuitiveMetricsReporter.java
> +    	pushGauge(metricName + ".1MinuteRate", meter.getOneMinuteRate());
These follow other tools Reporter implementation names

2017-02-10 14:47 UTC, joepusateri commented on src/test/docker/docker-compose.yml
> +    image: example/dropwizard
Using an image here names it in the local repo.  Doing this matches the image name given in the dockerBuildImage script.

2017-02-10 14:47 UTC, joepusateri commented on src/test/docker/docker-dropwizard-example/README.md
> +* JDK (to compile java file locally)
I don't know what to do with this

2017-02-10 14:48 UTC, joepusateri commented on src/test/docker/docker-dropwizard-example/dockerBuildImage.bat
> +docker build -t example/dropwizard:latest .
They are not necessary, but I found them useful.

2017-02-10 14:59 UTC, TheConnMan commented on src/test/docker/docker-dropwizard-example/README.md
> +* JDK (to compile java file locally)
The Zorka agent Dockerfile is an example of building all necessary artifacts within the container: https://github.com/Netuitive/zorka/blob/master/Dockerfile

2017-02-10 15:00 UTC, TheConnMan commented on src/test/docker/docker-compose.yml
> +    image: example/dropwizard
I see, it's for labeling the image, not using the image. Good to know.

2017-02-10 15:05 UTC, TheConnMan commented on src/test/docker/docker-dropwizard-example/dockerBuildImage.bat
> +docker build -t example/dropwizard:latest .
Feels like repo clutter to have 8 bat/sh scripts in the repo just to run one line java and docker commands. I understand they're helpful locally, but I don't think they should be checked in.

2017-02-10 15:08 UTC, TheConnMan commented on README.md
> +`./run_tests.sh`
Will any metrics come into Netuitive from Dropwizard without user written tests?

2017-02-10 15:09 UTC, TheConnMan commented on README.md
> +docker-compose up -d --build
https://github.com/Netuitive/dropwizard-metrics/pull/1#discussion_r100550875 is the more relevant discussion for this, let's continue there.

2017-02-10 15:11 UTC, joepusateri commented on README.md
> +`./run_tests.sh`
TBH I am not sure what these tests would consist of.  Once started the dropwizard example will report metrics once per minute with mostly zero values.

2017-02-10 15:34 UTC, joepusateri commented on src/test/docker/docker-dropwizard-example/dockerBuildImage.bat
> +docker build -t example/dropwizard:latest .
I will remove them

2017-02-14 20:47 UTC, TheConnMan approved these changes

2017-02-14 20:48 UTC, merged